package com.gprs.uttarpradesh;

import android.location.Address;
import android.location.Geocoder;
import android.os.Bundle;
import android.os.Environment;
import android.util.Log;
import android.util.Pair;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

import com.google.gson.Gson;

import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class testing extends AppCompatActivity {


    String select;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_testing);


        String[] hos = {"DISTRICT HOSPITAL AHMEDNAGAR,Pin- 414001",
                "Booth Hospital Ahmednagar,Pin- 414001",
                "MH",
                "AIIMS Hospital Ahmednagar,Pin- 414001",
                "Govt Medical College, Akola",
                "OZONE Hospital,Akola",
                "ICON Hospital, Akola",
                "Panjabrao Deshmukh Medical College Amravati",
                "Sub District Hospital Achalpur",
                "Dhole Homoeopathic College Amravati",
                "Regional Referral Services Hospital Amravati",
                "BEST HOSPITAL, WALGAON ROAD, AMRAVATI",
                "Super Speciality Hospital GMHC,Aurangabad",
                "Dhoot Hospital (Proposed Emergency) Aurangabad",
                "MGM College Hospital (Proposed)Aurangab ad",
                "Medicin building (proposed) Aurangabad",
                "DH Beed",
                "Womens Hospital Ambajogai",
                "SRTR GMC Ambajogai",
                "Covid Hospital ( New MCH Wing Building) , General Hospital Campus, Bhandara",
                "Life Line Hospital Khamgaon",
                "Womens Hospital, New Building, Buldhana",
                "Silvercity Hospital Khamgaon",
                "SDH Shegaon",
                "Aashirwad Hospital Buldana",
                "GH Khamgaon",
                "Mehtre Hospital Buldhana",
                "Laddhad Hospital, Buldana",
                "Multispeciality Hospital Mehkar",
                "Rite Care Hospital Malkapur",
                "Christ Charitable Hospital (100 Bedeed)",
                "Manvatkar Multi Specialty Hospital",
                "Shivji Hospital & Eeg Center, Chandrapur",
                "Government Medical College & Hospital, Chandrapur",
                "Shri Bhausaheb Hire Government Medical College, Dhule",
                "GNM Nursing School DH Gadchiroli",
                "DH Gadchiroli",
                "GMC & KTS Hospital Gondia",
                "Central Hospital Gondia",
                "Gondia Care Hospital Gondia",
                "Sahyog Hospital Gondia",
                "corona hospital near bus stand",
                "District Hospital, Hingoli",
                "Divisional Railway Hospital",
                "DR. U. PATIL MEDICAL COLLEGE HOSPITAL",
                "GOLD CITY HOSPITAL, JALGAON",
                "GANPATI HOSPITALJALGAON",
                "Government Medical College, Jalgaon",
                "COVID-19 HOSPITAL DH JALNA",
                "Vivekanand Hospital",
                "Annex building D.H.JALNA",
                "Rajshree Shahu Goverment Medical college ,Kolhapur",
                "D Y Patil Hospital kolhapur",
                "MIMSR Medical College Latur",
                "VILASRAO DESHMUKH GOVERNMENT INSTITUTE OF MEDICAL SCIENCES, LATUR",
                "Latur Super Sepciality Hospital",
                "General Hospital Udgir",
                "Vivekanand Cardiac & Superspeciality Hospital",
                "Dr.L.H.Hiranandani Hospital",
                "APEX HOSPITAL",
                "Nanavati Super Speciality Hospital",
                "R. N. COOPER HOSPITAL",
                "Saifee Hospital",
                "nair hospital",
                "HOLY FAMILY HOSPITAL",
                "Breach candy",
                "kem hospital",
                "S. L. RAHEJA HOSPITAL",
                "Lilavati Hospital and Research Centre,",
                "MMRDA BKC Jumbo Facility - HE (Phase I)",
                "sion hospital",
                "GALAXY MULTISPECIALTY HOSPITAL",
                "Race Course Jumbo Facility - GS (Phase II)",
                "TATA MEMORIAL HOSPITAL",
                "Wockhardt Hospital",
                "SANJEEVANI HOSPITAL",
                "MMRDA BKC Jumbo Facility - HE (Phase II)",
                "MASINA HOSPITAL",
                "Jaslok Hospital",
                "CIDCO Mulund Jumbo Facility - T (Phase II)",
                "KOHINOOR HOSPITAL",
                "JAGJIVAN RAM HOSPITAL",
                "BHATIA HOSPITAL",
                "Seven Hill Reliance Hospital",
                "NAVNEET HI-TECH HOSPITAL",
                "Global Hospitals",
                "Race Course Jumbo Facility - GS (Phase I)",
                "APEX SUPER SPECIALITY",
                "APEX HOSPITAL -MULUND",
                "P. D. Hinduja",
                "Kasturba Hospital Mumbai",
                "GURUNANAK HOSPITAL",
                "MCGM SEVEN HILLS",
                "LIFELINE MEDICARE - GOREGAON",
                "Fortis hospital mumbai",
                "G.T. Hospital",
                "PRINCE ALY KHAN HOSPITAL",
                "Hinduhridaysamrat Balasaheb Thackeray Trauma Hospital Jogeshwari W",
                "SUSHRUSHA HOSPITAL Vikhroli",
                "K. J. Somaiya",
                "Saint George Hospital, Mumbai",
                "SRV HOSPITAL",
                "Mumbai Metro Dahisar Jumbo Facility - T (Phase II)",
                "NESCO Jumbo Facility - P South (Phase I)",
                "GMC Nagpur",
                "IGGMC",
                "MH",
                "AIIMS",
                "Lifecare Abhudyaya",
                "Dr Shankarrao Chavan GMC Nanded",
                "Yashosai Hospital Nanded",
                "SGGS District Hospital old building Nanded",
                "Global Hospital",
                "Aasha Hospital,Kabra nagar road, Nanded.",
                "SDH Mukhed",
                "Vithai Hospital Nanded",
                "Ashwini Hospital Nanded",
                "Sanjeevani Hospital",
                "Civil Hospital,Nandurbar (EYE HOSPITAL)",
                "DCH - Farhan Hospital,Malegaon",
                "DCH - SAHARA HOSPITAL",
                "DCH - MVP Medical College,Nashik",
                "MH",
                "DCH - Apollo Hospital,Nashik",
                "DCH - Ashoka Medicover Hospital",
                "DCH - Civil Hospital, Nashik (Kumbhmela building)",
                "DCH - Sahyadri Hospital",
                "District Hospital",
                "SDH Tuljapur",
                "SDH Omerga",
                "Vijayvallabh Hospital",
                "Vedanta Institute of Medical Science, 1st Building, Dahanu",
                "Golden Park Hospital",
                "Tima Hospital, Boisar",
                "Galaxy hospital",
                "Vinayaka Multi Speciality Hospital",
                "RIDDHI VINAYAK HOSPITAL",
                "Star Hospital",
                "Revera Hospital",
                "Dhavale Hospital,Palghar",
                "Tamboli Hospital Gulshan Bagh Parbhani",
                "Dr. Prafulla Patil Multi Super Speciality hospital ParbhÃ ni",
                "Parbhani ICU Doctor Line Parbhani",
                "Chirayu Hospital Doctor Line Parbhani",
                "Surya ICU Gavhane Chowk, Parbhani",
                "Swati Criticare Hospital Wasmat Road Parbhani",
                "Spandan ICU, Wasmat Road Parbhani",
                "Civil Hospital, Parbhani",
                "Pole Multi Speciality Hospital Jintur Road Parbhani",
                "Sahyadri Hospital, Hadapsar",
                "Bharti Vidyapeeth, Katraj, Pune",
                "Deenanth Mangeshkar Hospital",
                "Inlax & Budhrani Hospital, Koregaon Park",
                "Symbiosis University Hospital, Lavale",
                "Sahyadri Hospital Deccan",
                "Poona Hospital, Navi Peth",
                "Columbia Asia Hospital, PMC",
                "Sanjeevan Hospital, Karve Road",
                "Jehangir Hospital, PMC",
                "Deoyani multispeciality hospital, Kothrud",
                "ALC",
                "Ruby Hall Clinic PMC",
                "Lokmanya Hospital ,Nigdi",
                "Sassoon General Hospital COVID-19, Pune",
                "Aditya Birla hospital,Thergaon,Pune",
                "Comd Hosp",
                "DH Pune",
                "YASHWANTRAO CHAVAN MEMORIAL HOSPITAL PIMPRI",
                "KEM Hospital PMC",
                "Mimer Medical Collage & hospital , talegaon Dabhade",
                "Smt Kashibai Navale Medical College, Nerhe, Pune",
                "Noble Hospital Hadapsar",
                "Sub District Hospital Panvel",
                "MGM Hospital, Kamothe",
                "SUB DISTRICT HOSPITAL KALAMBANI",
                "District Hospital, Ratnagiri",
                "BKL Walawalkar Hospital, Derwan",
                "Wanless Hospital,Miraj",
                "Govt. Medical College and Hospital Miraj",
                "Bharati Vidyapeeth & Deemed University Medical College & Hospital Taluka -Miraj",
                "Prakash Hospital Islampur",
                "Sanjevaan Hospital Satara",
                "Sahyadri Hospital Karad",
                "Satara Hospital Satara",
                "Ajinkyatara Hospital Satara",
                "Krushna Hospital, Karad",
                "Sai Amrut Hospital Satara",
                "SAVITRI HOSPITAL Lonand",
                "Symbiosis Hospital, Satara",
                "JOGLEKAR HOSPITAL,SHIRWAL",
                "Minakshi Hospital, Satara",
                "Civil Hospital - Satara",
                "Patil Hospital Koregaon",
                "Samarth Hospital, Satara",
                "Siddhanath Hospital,Phaltan",
                "Yashwant DignosticsSatara",
                "Shriratna Hospital,Karad",
                "Mangalmurti Hospital Satara",
                "Shri Sidhivinayak Hospital,Lonand",
                "Pratibha Hospital Satara",
                "Nikop Hospipal Phaltan",
                "Satara Dignostics Satara",
                "Civil Hospital",
                "Shri C. S. M. S.Ruganalya, Solapur",
                "NARMADA MULTISPECIALITY HOSPITAL",
                "Jan Kalyan Hospital, Pandarpur",
                "GANGAMAI HOSPITAL",
                "CNS HOSPOITAL",
                "Yashodhara Hospital, SMC, Solapur",
                "Ashwini Rural Medical College and Hospital, Kumbhari",
                "Jagdale Mama Hospital, Barshi",
                "Lifeline Hospital Pandharpur",
                "Akluj CritiCare and Trauma Center, Akluj",
                "SIDDHESHWAR CANCER HOSPITAL",
                "Apex Hospital , Pandarpur",
                "Galaxy Hospital, Pandarpur",
                "CITY HOSPITAL",
                "ASHWINI SAHAKARI RUGNALAY",
                "VED HOSPITAL, KON GAON, KALYAN ROAD",
                "TMC: Vedant Hospital",
                "NMMC Vashi General Hospital",
                "TMC: Thane health Care",
                "KDMC VASANT VALLEY",
                "Maxlife hospital",
                "TMC: Prime horizon Hospitl Manpada",
                "NMMC Fortis hospital",
                "TMC :Metro pol Multispeciality",
                "KDMC SHIVAM HOSPITAL",
                "NMMC Terna Hospital, Nerul",
                "KDMC Sai Hospital",
                "Satya sai Platinum hospital",
                "IGM Bhiwandi",
                "TMC: New Thane COVID Hospital",
                "TMC: Siddhivinayak Maternity and General Hospital",
                "KDMC A&G HOSPITAL KALYAN",
                "NMMC Apollo Hospital, Belapur",
                "TMC: Kaushalya Hospital",
                "TMC: Lake City Hospital",
                "TMC: Wellam Hospital & Diagnostic Centre",
                "TMC: Life Care Hospital",
                "KDMC SHWAS MULTI SPECIALITY",
                "KDMC Holy Cross",
                "TMC: Param Hospital & ICU",
                "TMC: Fortune Plus ICU & Multispeciality Hospital LLP",
                "KDMD C.B. VAIDYA MEMORIAL HOSPITAL KALYAN",
                "KDMC Neon Hospital",
                "KDMC Baj R.R. Hospital",
                "MBMC - Pandit Bhimsen Joshi Hospital",
                "TMC: Swayam Hospital",
                "TMC: Infinity Medi- Surge Center",
                "KDMC STAR CITY MULTI SPECIALTY",
                "NMMC MPCT Hospital",
                "TMC: Civil Hospital Thane ,",
                "TMC: Oscar Multispeciality Hospital",
                "TMC: Jito Educational & Medical Trust",
                "NMMC MGM Hospital",
                "KDMC Sai Arogyam Hospital",
                "MBMC - Galaxy Hospital",
                "TMC: Sapphire Hospital",
                "TMC: Titan Hospital",
                "MBMC - Sheth P V Doshi Hospital",
                "TMC: Neon Hospital",
                "MBMC - Family Care Hospital",
                "NMMC PKC Hospital",
                "Women Hospital, Ulhasnagar 4",
                "MBMC - Neptune Hospital",
                "TMC: Aaarogyan Multispeciality Hospital",
                "TMC: Highway Hospital",
                "KDMC C.B. VAIDYA MEMORIAL HOSPITAL KALYAN",
                "KDMC Optilife Hospital",
                "S S Hospital",
                "TMC: Kalsekar Hospital",
                "Ambernath city Hospital",
                "MBMC - Wockhardt Hospital",
                "KDMC LALCHOWKI BOT KALYAN",
                "KDMC Sidhivinayak Multi Specialty Hospital",
                "SS HOSPITAL, KALHER",
                "MBMC - Thunga Hospital",
                "NMMC Reliance Hospital KK",
                "KDMC RUKMINIBAI PLAZA TITWALA",
                "MGIMS, Sewagram",
                "AVBRH Sawangi Meghe",
                "DEIC Building, District Hospital Campus, Washim",
                "VNGMC Yavatmal",
                "Malpani Hospital Sangamner,Pin- 422605",
                "CRHP Jamkhed,Pin- 413201",
                "Atma Malik Hospital Kokamthan,Koperga on,Pin-423603",
                "Sanjivani Hospital Sangamner,Pin- 422605",
                "Sai Baba Hospital,Shirdi,Pin- 423109",
                "Shri Krushna Accident Hospital,Rahuri,Pin- 413705",
                "Dr.Bhandkoli Hospital Akole,Pin- 422601",
                "Dr.Korde Hospital,Rahuri,Pin- 413705",
                "Sai Nath Hospital Shirdi,Rahata,Pin- 423109",
                "Swami Vivekanand Nursing Home Ayurvedic College Rahuri Factory,Rahuri,Pin- 413705",
                "Saint Luks Hospital, Shrirampur ,Pin- 413709",
                "SDH Pathardi,Pin- 414102",
                "Niramay Hospital Supa,Parner,Pin- 414301",
                "Moredada Hospital Shrigonda,Pin- 413701",
                "Omkar Hospital Supa,Parner,Pin- 414301",
                "F.J.F.M Wadala Mission Hospital, Wadla Bahiroba,Newasa,Pin- 414602",
                "Swami Vivekanand Multispeciality Hospital And Aurvedic Research Centre PARGAON SHRIGONDA,413701",
                "Dr.Bule Hospital, Akole,Pin-422601",
                "Shaneshwar Gramin Rugnalay, Shingnapur,Newasa, Pin-414105",
                "RH Shevgaon,Pin- 414502",
                "Sub District Hospital, Karjat,Pin-414402",
                "Rural Hospital Chichondi Patil,Nagar,Pin-414201",
                "ORBIT Hospital, Akola",
                "Sahara Hospital, Akola",
                "City Hospital, Akola",
                "District Women Hospital, Akola",
                "Sub District Hospital Murtizapur",
                "GMC Akola New Building",
                "RKT ( Radhakishan Toshniwal Hospital ), Akola",
                "Sub District Hospital Daryapur",
                "Sub District Hospital Morshi",
                "Gurudeo Ayurved Collage Mozari Amravati",
                "Dr Gode Ayurved Collage Amravati",
                "RRSH Phase II F2",
                "UPJILHA RUGNALAY SILLOD",
                "Mahatma Gandhi Memorial Hospital",
                "TRAMA CARE PACHOD, PAITHAN",
                "CHATRAPATI SHAHU MAHARAJ AYURVEDIC & DENTAL COLLEGE & HOSPITAL AURANGABAD",
                "Employment State Insurance Scheme(ESIS),pl.no.1 6,Naregaon road,near Garware stadium.Chikhalthan a.",
                "CIVIL HOSPITAL CHIKALTHANA AURANGABAD",
                "RURAL HOSPITAL AJINTHA, SOYGOAN",
                "Central Institute of Plastics Engineering and Technology(CIPET),M eltron Building ,MIDC,Chikhalthana",
                "ANAND HOSPITAL VAIJAPUR",
                "TRAMA CARE CENTER GANGAPUR",
                "S.D.H. TRAMA VAIJAPUR",
                "Y. S. I. G. M.HOSPITAL CIDCO N-5 AURANAGABAD",
                "Dr Hedgewar Hospital",
                "GAJANAN HOSPITAL BIDKIN TQ. PAITHAN",
                "Kamalnayan Bajaj Hospital",
                "TRAMA CARE CENTER KANNAD",
                "Vithai Hospital & reserach Center, Beed",
                "WH Quarters,Ambajogai",
                "Trauma Care Unit Telgaon",
                "SDH Kaij",
                "Sau.Kesharbai Kshirsagar Hospital Beed",
                "Trauma Care Unit Georai",
                "Lifeline Multispeciality surgical Hospital Beed",
                "Munde Children Hospital, Parali",
                "Paradise Hospital Beed",
                "SDH Parali",
                "Trauma Care Unit Ashti",
                "Veer Hospital Beed",
                "Geriatric Hospital Ambajogai",
                "Karad Hospital, Parali",
                "Spandan Hospital beed",
                "Shatayushi Hospital Majalgaon",
                "Yashvant Hospital & Criticare, Majalgaon",
                "Gholve Hospital Beed",
                "Manik Hospital, Georai",
                "Tidke hospital beed",
                "TB Ward Building G H Campus Bhandara",
                "New Nursing School Hostel, Bhandara",
                "Paying Ward G H Bhandara",
                "Opthalmic Ward Building , G H Campus Bhandara",
                "Mohata Hospital, Nandura",
                "Hiwrashram Hospital, Hiwra , Ta Mehakar",
                "Chunawale Hospital, Chikhali",
                "Tuljai Hospital, Chikhali",
                "Chopade Hospital Malkapur",
                "Lahoti Hospital, Sultanpur, Ta- Lonar",
                "Homiopathic Hospital (panchshil) ,Khamgaon",
                "City Hospital, Buldana",
                "Gajanan Maharaj Santhan Hospital,Shegaon",
                "Shweta Hospital Chandrapur",
                "Spandan Heart & Child (Zade) Hospital, Chandrapur",
                "Sub District Hospital Rajura",
                "Shri Vyankatesh Hospital & Research Center (Wasalwar)",
                "Bukkawar Hospital, Chandrapur",
                "Sai Divine Cure Multy Sepciality Hospital",
                "Coal City Hospital (Dr Poddar)",
                "Pant Hospital Chandrapur",
                "Vardhman Education & Welfare Society Dondaicha",
                "Medical College Boradi",
                "Civil Hospital Dhule",
                "SDH Dondaicha",
                "SDH Shirpur",
                "New Construction PHC Building Alapalli",
                "SDH Kurkheda",
                "SDH Armori",
                "Dharmashala DH Gadchiroli",
                "MS Ayurvedic College Kudwa Gondia",
                "KTS DH Gondia General Hospital Gondia",
                "Sub District Hospital Tirora",
                "kautha hospital",
                "sub dist hospital basmat",
                "Sub. District Hospital ,Kalamnuri",
                "NRUSINH HOSPITAL CHOPDA",
                "RURAL HOSPITAL , AMALNER",
                "RAILWAY HOSPITAL , TQ BHUSAWAL",
                "SIDDIVINAYAK HOSPITAL,PACHORA",
                "SDH Muktainagar",
                "SDH Chopda",
                "VIGNAHARTA HOSPITAL PACHORA",
                "Guru Mishri Homeopathy Medical College,Shelgaon,Tq Badnapur",
                "Mission Hospital",
                "Dr. Ved Prakash Ayurvedic Medical College Ambewadi,Jalna",
                "Deepak Hospital",
                "JIIU RESEARCH CENTRE & MEDICAL COLLEGE WARUDI",
                "GNM Nursing College DH Jalna",
                "Dr. J J Magdum Ayurvedic Medical college & Hospital",
                "Athayu Hospital,Ujalawadi pune-Banglour highway",
                "Isolation Hospital",
                "Mahatma Gandhi Hospital",
                "Sanjay Ghodawat College,Atigre",
                "Kedar Redekar Hospital",
                "Department of Telecommunication,s hivaji University",
                "Sant Gajanan Hospital",
                "Nilanga SDH II",
                "Udaygiri Lions Eye Hospital Udgir",
                "B S F Chakur",
                "MIMSR Medical College II",
                "Fulabai Bansude Hospital, Latur",
                "Patil Hospital",
                "NSCI Dome Jumbo Facility - GS",
                "Maharashtra Nature Park (Dharavi) Jumbo Facility - GN",
                "SVD Savarkar Hospital Mulund",
                "HINDU SABHA",
                "Kanakia Ground Chembur Jumbo Facility - MW (Phase III)",
                "Rajawadi Hospital, Ghatkopar (E)",
                "NOWROSJEE WADIA MATERNITY HOSPITAL",
                "BSES MG GENERAL HOSPITAL",
                "THUNGA HOSPITAL",
                "Ackworth Leprosy Hospital",
                "Pt. M.M. Malviya Centenary Hospital, Govandi (E",
                "K B BHABHA HOSPITAL, BANDRA",
                "KARUNA HOSPITAL",
                "EYE HOSPITAL",
                "Worli Police Ground Jumbo Facility - GS (Phase III)",
                "Maa Hospital, Chembur",
                "Employees' State Insurance scheme Hospital",
                "NESCO",
                "K.B. Bhabha Hospital, Kurla (W)",
                "NH SRCC Children's Hospital",
                "Gilder Lane School Jumbo Facility - E (Phase III)",
                "Bhagwati Hospital, NTC Bldg., Borivali (W)",
                "CAMA HOSPITAL",
                "Bombay Hospital",
                "Famous Studio Bandra Jumbo Facility - HW (Phase III)",
                "LIFELINE HOSPITAL - KANDIVALI",
                "M.W. Desai Hospital, Malad (E)",
                "Bharat Ratna Dr Babasaheb Ambedkar Municipal",
                "General Hospital",
                "Jio Convention Centre Jumbo Facility",
                "- HE (Phase III)",
                "S.K. Patil Hospital, Malad (E)",
                "JNPT Hospital",
                "Sushrusha Hospital, Dadar",
                "Najam Baug Jumbo Facility - B (Phase II)",
                "V.N. Desai Hospital, Santacruz(E)",
                "Richardson and Cruddas Jumbo Facility - E (Phase II)",
                "Mumbai Port Trust Hospital",
                "ENT Hospital",
                "Bombay Tobacco",
                "Studio Juhu Jumbo",
                "Facility - KW (Phase III)",
                "Filmistan Goregaon Jumbo Facility - PS (Phase III)",
                "Malad Infiniti Mall",
                "Jumbo Facility - PN (Phase III)",
                "NESCO Jumbo",
                "Facility - P South (Phase II)",
                "Divisional Railway Hospital",
                "CH",
                "Govt Ayurvedic",
                "Medical college Nanded"};

        select = "maharastra";

        ArrayList<Pair<Double, Double>> arrayString = new ArrayList<>();


        ArrayList<String> district = new ArrayList<String>(Arrays.asList(hos));

        for (int j = 0; j < district.size(); j++) {
            Geocoder geocoder = new Geocoder(getBaseContext());
            List<Address> addresses;
            try {
                addresses = geocoder.getFromLocationName(district.get(j) + ',' + select, 20);


                double latitude = addresses.get(0).getLatitude();
                double longitude = addresses.get(0).getLongitude();

                arrayString.add(new Pair<Double, Double>(latitude, longitude));


            } catch (Exception e) {

            }

        }

        TextView textView = findViewById(R.id.text);
        textView.setText(arrayString.toString());
        Gson gson = new Gson();

        String json = gson.toJson(arrayString);


        writeToFile(json);

    }

    private void writeToFile(String data) {
        String extStorageDirectory = Environment.getExternalStorageDirectory()
                .toString();
        File f = new File(extStorageDirectory + "/COVI19RELIEF/list/" + select + ".txt");

        if (!f.exists()) {
            try {

                File folder1 = new File(extStorageDirectory, "COVI19RELIEF");// Name of the folder you want to keep your file in the local storage.
                folder1.mkdir(); //creating the folder
                File folder2 = new File(folder1, "list");// Name of the folder you want to keep your file in the local storage.
                folder2.mkdir(); //creating the folder
                File file = new File(folder2, select + ".txt");
                file.createNewFile(); // creating the file inside the folder
            } catch (Exception e) {

            }
        }
        try {
            FileOutputStream file = new FileOutputStream(f);
            DataOutputStream fileOutputStream = new DataOutputStream(file);
            fileOutputStream.writeBytes(data);
        } catch (IOException e) {
            Log.e("Exception", "File write failed: " + e.toString());
        }
    }
}

